### ISSUE TITLE
[Async Storage, Gameplay, Android & iOS]Return to Home doesn't save progress

### ISSUE THREAD

**Issue by jlatour3** [GTBitsOfGood/brain-exercise#80]
If you press the "return to home" button in the pause screen, you have to restart the whole session of exercises. It doesn't pick up where you left off. - according to Raymond.

**Comment by jlatour3** [comment]
Also tried this, got through 1 x math, 1 x writing, 1 x reading and then returned to home using pause feature during 2nd section of math. Tapped "start exercises" again, got the "You will be doing a mixture of reading, writing, and math " screen so I assume it restarts.

**Comment by shopaniuk** [comment]
So this isn't a bug, it's a feature that was never implemented; the pause screen is for resuming progress. If we are going to implement this here are some things to consider @jlatour3 :
-If the HomeScreen is in the paused state, does it look any different?
-Does the paused version of the HomeScreen become the normal HomeScreen (i.e ResumeHome becomes StartExerciseHome after some period of inactivity)
-The easiest way to get around all of this is to have the Pause screen only have a resume button.

I don't think I'll have time to do this before Sunday @DeveloperKhan. The easiest way to do this is probably to use canGoBack() + goBack()/pop(2) for the navigator since it would use history. Otherwise we'd have to preserve the progress in local AsyncStorage

**Comment by jlatour3** [comment]
Take away the option to "return to home". @shopaniuk, Can we ensure that the screen will stay on resume until the user finishes their session, so that progress is not lost?

**Comment by DeveloperKhan** [comment]
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-01 at 15 51 40](https://user-images.githubusercontent.com/26877561/91899379-0f441f80-ec6b-11ea-9e63-e8e639e9297e.png)

Here's my solution

**Comment by jlatour3** [comment]
I like it
